export const PERMISOS = Object.freeze({
  USUARIOS: {
    VIEW: 'VIEW_USUARIOS',
    CREATE: 'CREATE_USUARIOS',
    READ: 'READ_USUARIOS',
    UPDATE: 'UPDATE_USUARIOS',
    DELETE: 'DELETE_USUARIOS',
  },
  ROLES: {
    VIEW: 'VIEW_ROLES',
    CREATE: 'CREATE_ROLES',
    READ: 'READ_ROLES',
    UPDATE: 'UPDATE_ROLES',
    DELETE: 'DELETE_ROLES',
  },
  PERMISOS: {
    VIEW: 'VIEW_PERMISOS',
    CREATE: 'CREATE_PERMISOS',
    READ: 'READ_PERMISOS',
    UPDATE: 'UPDATE_PERMISOS',
    DELETE: 'DELETE_PERMISOS',
  }
});